### ISSUE TITLE
Missing configuration file

### ISSUE THREAD

**Issue by strasserpatrick** [mobiletomb/IS-MIM#1]
Hello, thanks for sharing your code of the paper and the nice work!

I would like to get your project running, but I think you missed adding your configuration file used for the run command.

When running `run_training_mim.py`:
```bash
from nnunet.run.default_configuration import get_my_configuration
ImportError: cannot import name 'get_my_configuration' from 'nnunet.run.default_configuration'
```

Could you share the method you used here? That would be nice. Otherwise the repo is not useful without guessing your configuration

Thank you in advance!

**Comment by strasserpatrick** [comment]
Same for this piece of code:

```python
from nnunet.utilities.nd_softmax import softmax_helper, identity
```

Here, identity is not part of nnunetv1

**Comment by LcQi-mic** [comment]
Hi, Thank you for your interest in this work

We use the default configuration that is automatically created by nnUNet. The 'get_my_configuration' is only used when we test the influence of depth of the used U-net architecture. 

About the issue of "from nnunet.utilities.nd_softmax import softmax_helper, identity":
      The identity is a simple Lambda Expression:  " identity = lambda  x: x "

We hope our paper can help you.

**Comment by strasserpatrick** [comment]
Thank you very much for your fast response!
